import { ActivityResponse } from '../api';
import { getActivityCoverImage } from './activityAssets';

export const curatedActivities: ActivityResponse[] = [
  {
    id: 'template-1',
    title: 'Sunset rooftop dinner',
    category: 'Food',
    location: 'Downtown Skyline',
    description: 'An elevated evening with small plates, thoughtful conversation, and city views.',
    date: 'Tonight',
    time: '7:30 PM',
    distance: '1.1 km',
    vibe: 'Curated',
    attendees: 6,
    maxAttendees: 10,
    spotsLeft: 4,
    costType: 'Paid',
    costAmount: 45,
    currency: 'AUD',
    venueName: 'Skyline House',
    exactAddress: 'Downtown rooftop terrace',
    startTime: '7:30 PM',
    endTime: '10:00 PM',
    hostRating: 4.9,
    hostHostedCount: 18,
    hostVerified: true,
    coverImage: getActivityCoverImage('Food', 'template-1'),
    availabilityTag: 'Tonight',
    host: 'Avery',
    hostId: 'host-1',
    hostAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Mia' },
      { name: 'Ava' },
      { name: 'Noah' },
    ],
  },
  {
    id: 'template-2',
    title: 'Morning hike + coffee',
    category: 'Adventure',
    location: 'River Trail',
    description: 'A scenic 5K with a coffee stop for easy pace, good company, and fresh air.',
    date: 'Saturday',
    time: '9:00 AM',
    distance: '2.4 km',
    vibe: 'Active',
    attendees: 8,
    maxAttendees: 12,
    spotsLeft: 4,
    costType: 'Free',
    venueName: 'River Trail',
    exactAddress: 'Main trail entrance',
    startTime: '9:00 AM',
    endTime: '11:30 AM',
    hostRating: 4.8,
    hostHostedCount: 11,
    hostVerified: true,
    coverImage: getActivityCoverImage('Adventure', 'template-2'),
    availabilityTag: 'This weekend',
    host: 'Jordan',
    hostId: 'host-2',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Eli' },
      { name: 'Sofia' },
      { name: 'Ryan' },
    ],
  },
  {
    id: 'template-3',
    title: 'Creative co-working lounge',
    category: 'Networking',
    location: 'Union House',
    description: 'Make progress, exchange ideas, and stay inspired with a curated work circle.',
    date: 'Monday',
    time: '3:00 PM',
    distance: '800 m',
    vibe: 'Focused',
    attendees: 5,
    maxAttendees: 8,
    spotsLeft: 3,
    costType: 'Free',
    venueName: 'Union House',
    exactAddress: 'Union House lounge',
    startTime: '3:00 PM',
    endTime: '5:30 PM',
    hostRating: 5,
    hostHostedCount: 9,
    hostVerified: true,
    coverImage: getActivityCoverImage('Networking', 'template-3'),
    availabilityTag: 'Tomorrow',
    host: 'Sam',
    hostId: 'host-3',
    hostAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Lina' },
      { name: 'Theo' },
      { name: 'Grace' },
    ],
  },
];

export const getCuratedActivity = (id: string) => curatedActivities.find((activity) => activity.id === id);
