import { ActivityResponse } from '../api';
import { getActivityCoverImage } from './activityAssets';

export const curatedFakeUsers = [
  { id: 'fake-user-1', name: 'Marco Bianchi', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-2', name: 'Sofia Rossi', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-3', name: 'Alex Kim', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-4', name: 'Liam Carter', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-5', name: 'Emma Watson', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-6', name: 'Olivia Green', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-7', name: 'Noah Bennett', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-8', name: 'Mia Chen', avatar: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-9', name: 'Ethan Brooks', avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-10', name: 'Ava Patel', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-11', name: 'Lucas Stone', avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-12', name: 'Isabella Moore', avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-13', name: 'Henry Wilson', avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-14', name: 'Amelia Clarke', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=200&q=80' },
  { id: 'fake-user-15', name: 'Jack Taylor', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=200&q=80' },
];

const people = (start: number, count: number) =>
  Array.from({ length: count }, (_, index) => curatedFakeUsers[(start + index) % curatedFakeUsers.length]);

const curatedActivityData: ActivityResponse[] = [
  {
    id: 'template-1',
    title: 'Sunset rooftop dinner',
    category: 'Food',
    location: 'Downtown Skyline',
    description: 'An elevated evening with small plates, thoughtful conversation, and city views.',
    date: 'Tonight',
    time: '7:30 PM',
    distance: '1.1 km',
    vibe: 'Curated',
    attendees: 6,
    maxAttendees: 10,
    spotsLeft: 4,
    costType: 'Paid',
    costAmount: 45,
    currency: 'AUD',
    venueName: 'Skyline House',
    exactAddress: 'Downtown rooftop terrace',
    startTime: '7:30 PM',
    endTime: '10:00 PM',
    hostRating: 4.9,
    hostHostedCount: 18,
    hostVerified: true,
    coverImage: getActivityCoverImage('Food', 'template-1'),
    availabilityTag: 'Tonight',
    host: 'Avery',
    hostId: 'host-1',
    hostAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Mia' },
      { name: 'Ava' },
      { name: 'Noah' },
    ],
  },
  {
    id: 'template-2',
    title: 'Morning hike + coffee',
    category: 'Adventure',
    location: 'River Trail',
    description: 'A scenic 5K with a coffee stop for easy pace, good company, and fresh air.',
    date: 'Saturday',
    time: '9:00 AM',
    distance: '2.4 km',
    vibe: 'Active',
    attendees: 8,
    maxAttendees: 12,
    spotsLeft: 4,
    costType: 'Free',
    venueName: 'River Trail',
    exactAddress: 'Main trail entrance',
    startTime: '9:00 AM',
    endTime: '11:30 AM',
    hostRating: 4.8,
    hostHostedCount: 11,
    hostVerified: true,
    coverImage: getActivityCoverImage('Adventure', 'template-2'),
    availabilityTag: 'This weekend',
    host: 'Jordan',
    hostId: 'host-2',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Eli' },
      { name: 'Sofia' },
      { name: 'Ryan' },
    ],
  },
  {
    id: 'template-3',
    title: 'Creative co-working lounge',
    category: 'Networking',
    location: 'Union House',
    description: 'Make progress, exchange ideas, and stay inspired with a curated work circle.',
    date: 'Monday',
    time: '3:00 PM',
    distance: '800 m',
    vibe: 'Focused',
    attendees: 5,
    maxAttendees: 8,
    spotsLeft: 3,
    costType: 'Free',
    venueName: 'Union House',
    exactAddress: 'Union House lounge',
    startTime: '3:00 PM',
    endTime: '5:30 PM',
    hostRating: 5,
    hostHostedCount: 9,
    hostVerified: true,
    coverImage: getActivityCoverImage('Networking', 'template-3'),
    availabilityTag: 'Tomorrow',
    host: 'Sam',
    hostId: 'host-3',
    hostAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Lina' },
      { name: 'Theo' },
      { name: 'Grace' },
    ],
  },
  {
    id: 'template-4',
    title: 'Singles sunset walk',
    category: 'Dating & Singles',
    location: 'Kata Beach',
    description: 'Meet potential partners through a relaxed group sunset walk and easy conversation by the beach.',
    date: 'Friday',
    time: '5:45 PM',
    distance: '1.6 km',
    vibe: 'Meet through activities',
    attendees: 7,
    maxAttendees: 12,
    spotsLeft: 5,
    costType: 'Free',
    venueName: 'Kata Beach',
    exactAddress: 'Kata Beach north entrance',
    startTime: '5:45 PM',
    endTime: '7:00 PM',
    hostRating: 4.8,
    hostHostedCount: 7,
    hostVerified: true,
    coverImage: getActivityCoverImage('Dating & Singles', 'template-4'),
    availabilityTag: 'Friday',
    host: 'Nora',
    hostId: 'host-4',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    participants: [
      { name: 'Kai' },
      { name: 'Maya' },
      { name: 'Ben' },
    ],
  },
  {
    id: 'fake-activity-1',
    title: 'Pizza & Wine Night 🍕',
    category: 'Food',
    location: 'Perth CBD',
    description: 'Share wood-fired pizza, wine, and relaxed conversation in the city.',
    date: 'Friday',
    time: '7:00 PM',
    distance: '900 m',
    vibe: 'Warm',
    attendees: 4,
    maxAttendees: 8,
    spotsLeft: 4,
    coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Friday',
    host: curatedFakeUsers[0].name,
    hostId: curatedFakeUsers[0].id,
    hostAvatar: curatedFakeUsers[0].avatar,
    participants: people(1, 4),
  },
  {
    id: 'fake-activity-2',
    title: 'Sunrise Beach Run 🏃',
    category: 'Sports',
    location: 'Cottesloe Beach',
    description: 'Start the day with good vibes, ocean air, and a refreshing run.',
    date: 'Saturday',
    time: '6:30 AM',
    distance: '2.1 km',
    vibe: 'Energising',
    attendees: 6,
    maxAttendees: 14,
    spotsLeft: 8,
    coverImage: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Saturday',
    host: curatedFakeUsers[1].name,
    hostId: curatedFakeUsers[1].id,
    hostAvatar: curatedFakeUsers[1].avatar,
    participants: people(2, 6),
  },
  {
    id: 'fake-activity-3',
    title: 'Hidden Cocktail Bar 🍸',
    category: 'Drinks',
    location: 'Northbridge',
    description: 'A low-lit cocktail table with a small group and easy introductions.',
    date: 'Friday',
    time: '8:30 PM',
    distance: '1.4 km',
    vibe: 'Low-lit',
    attendees: 5,
    maxAttendees: 9,
    spotsLeft: 4,
    coverImage: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Tonight',
    host: curatedFakeUsers[6].name,
    hostId: curatedFakeUsers[6].id,
    hostAvatar: curatedFakeUsers[6].avatar,
    participants: people(7, 5),
  },
  {
    id: 'fake-activity-4',
    title: 'Kayaking Adventure 🛶',
    category: 'Outdoors',
    location: 'Matilda Bay',
    description: 'Paddle calm water and enjoy beautiful views with a small crew.',
    date: 'Saturday',
    time: '10:00 AM',
    distance: '3.2 km',
    vibe: 'Scenic',
    attendees: 3,
    maxAttendees: 9,
    spotsLeft: 6,
    coverImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Weekend',
    host: curatedFakeUsers[4].name,
    hostId: curatedFakeUsers[4].id,
    hostAvatar: curatedFakeUsers[4].avatar,
    participants: people(5, 3),
  },
  {
    id: 'fake-activity-5',
    title: 'Yoga in the Park 🧘',
    category: 'Wellness',
    location: 'Kings Park',
    description: 'Gentle movement, quiet breathing, and golden morning light.',
    date: 'Sunday',
    time: '8:00 AM',
    distance: '1.9 km',
    vibe: 'Calm',
    attendees: 7,
    maxAttendees: 13,
    spotsLeft: 6,
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Sunday',
    host: curatedFakeUsers[5].name,
    hostId: curatedFakeUsers[5].id,
    hostAvatar: curatedFakeUsers[5].avatar,
    participants: people(6, 7),
  },
  {
    id: 'fake-activity-6',
    title: 'Founder Breakfast',
    category: 'Networking',
    location: 'Elizabeth Quay',
    description: 'Meet builders and founders over coffee, ideas, and momentum.',
    date: 'Tuesday',
    time: '8:15 AM',
    distance: '1.0 km',
    vibe: 'Focused',
    attendees: 5,
    maxAttendees: 10,
    spotsLeft: 5,
    coverImage: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Tuesday',
    host: curatedFakeUsers[11].name,
    hostId: curatedFakeUsers[11].id,
    hostAvatar: curatedFakeUsers[11].avatar,
    participants: people(12, 5),
  },
  {
    id: 'fake-activity-7',
    title: 'Live Jazz Table 🎷',
    category: 'Nightlife',
    location: 'Perth CBD',
    description: 'A small table for live jazz, drinks, and new company.',
    date: 'Thursday',
    time: '8:00 PM',
    distance: '1.3 km',
    vibe: 'Cinematic',
    attendees: 4,
    maxAttendees: 8,
    spotsLeft: 4,
    coverImage: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Thursday',
    host: curatedFakeUsers[12].name,
    hostId: curatedFakeUsers[12].id,
    hostAvatar: curatedFakeUsers[12].avatar,
    participants: people(0, 4),
  },
  {
    id: 'fake-activity-8',
    title: 'Social Tennis Rally 🎾',
    category: 'Sports',
    location: 'Leederville',
    description: 'Casual doubles, light competition, and a drink afterwards.',
    date: 'Sunday',
    time: '4:30 PM',
    distance: '2.7 km',
    vibe: 'Playful',
    attendees: 4,
    maxAttendees: 8,
    spotsLeft: 4,
    coverImage: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Sunday',
    host: curatedFakeUsers[14].name,
    hostId: curatedFakeUsers[14].id,
    hostAvatar: curatedFakeUsers[14].avatar,
    participants: people(1, 4),
  },
  {
    id: 'fake-activity-9',
    title: 'Rooftop Sundowners',
    category: 'Drinks',
    location: 'Perth CBD',
    description: 'Golden-hour drinks on a rooftop with an intimate crew.',
    date: 'Friday',
    time: '5:45 PM',
    distance: '1.1 km',
    vibe: 'Golden hour',
    attendees: 5,
    maxAttendees: 10,
    spotsLeft: 5,
    coverImage: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Friday',
    host: curatedFakeUsers[9].name,
    hostId: curatedFakeUsers[9].id,
    hostAvatar: curatedFakeUsers[9].avatar,
    participants: people(10, 5),
  },
  {
    id: 'fake-activity-10',
    title: 'Mindful Walk',
    category: 'Wellness',
    location: 'Matilda Bay',
    description: 'A slow reset walk with quiet chats and water views.',
    date: 'Monday',
    time: '7:30 AM',
    distance: '2.5 km',
    vibe: 'Restorative',
    attendees: 6,
    maxAttendees: 11,
    spotsLeft: 5,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=85',
    availabilityTag: 'Monday',
    host: curatedFakeUsers[19 % curatedFakeUsers.length].name,
    hostId: curatedFakeUsers[19 % curatedFakeUsers.length].id,
    hostAvatar: curatedFakeUsers[19 % curatedFakeUsers.length].avatar,
    participants: people(3, 6),
  },
];

// Curated/demo plans use verified real place centers so Map Mode can exercise
// the same coordinate path as API activities without inventing random offsets.
const curatedLocationCoordinates: Record<string, { latitude: number; longitude: number }> = {
  'Kata Beach': { latitude: 7.8214, longitude: 98.2962 },
  'Perth CBD': { latitude: -31.9523, longitude: 115.8613 },
  'Cottesloe Beach': { latitude: -31.9949, longitude: 115.7511 },
  Northbridge: { latitude: -31.9475, longitude: 115.8587 },
  'Matilda Bay': { latitude: -31.9778, longitude: 115.8249 },
  'Kings Park': { latitude: -31.9617, longitude: 115.8324 },
  'Elizabeth Quay': { latitude: -31.9587, longitude: 115.8575 },
  Leederville: { latitude: -31.9364, longitude: 115.8419 },
};

export const curatedActivities: ActivityResponse[] = curatedActivityData.map((activity) => ({
  ...activity,
  ...curatedLocationCoordinates[activity.location],
}));

export const getCuratedActivity = (id: string) => curatedActivities.find((activity) => activity.id === id);
